### PR TITLE
Gdaes 3467 update to latest and add serverspec

### PR DESCRIPTION
**Pull request by CrawfishPress**
Pulling in 15 commits from poise/supervisor, updating syntax, adding basic serverspec tests

### CODE REVIEW

**Comment by CrawfishPress** [comment]
test this please or face the consequences.

Darn-it... called my bluff...

**Comment by CrawfishPress** [comment]
Jenkins PR tests actually passed, just didn't notify.

http://jenkins-master-chef.awsdev.usatoday.com/job/supervisor_pulls/5/console

**Comment by CrawfishPress** [comment]
Do not merge, commit-job disabled for the moment.

**Comment by fhanson** [comment]
test this please

**Comment by fhanson** [comment]
test this please

**Pull request merged**
